# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 13:02
from __future__ import unicode_literals

import asymmetric_jwt_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asymmetric_jwt_auth', '0003_auto_20151112_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='key',
            field=models.TextField(help_text="The user's RSA public key", validators=[asymmetric_jwt_auth.models.validate_public_key]),
        ),
    ]
