# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asymmetric_jwt_auth', '0004_auto_20191104_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickey',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
